version: '3.8'

services:
  q_learning_app:
    build: .
    container_name: qlearning_hotwire_server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1